exclude_dirs: ['tests', 'venv', '.github', 'static', 'templates', '__pycache__', 'logs', 'postgresql_portable']

skips:
  - B105


tests:
  - B201
  - B301
  - B302
  - B303
  - B501
  - B502
  - B601
  - B602
  - B603
  - B607